`Loglikig` <-
function(x,kernel="normal",nu.fixed=2.0){
if(kernel=="normal"){
estimate<-mleig(x,kernel="normal")
mu<-estimate$mu
lambda<-estimate$lambda
f<-dig(x,mu,lambda,kernel="normal")
l<-log(f)
Loglik<-sum(l)
}
if(kernel=="logistic"){
estimate<-mleig(x,kernel="logistic")
mu<-estimate$mu
lambda<-estimate$lambda
f<-dig(x,mu,lambda,kernel="logistic")
l<-log(f)
Loglik<-sum(l)
}
if(kernel=="Laplace"){
estimate<-mleig(x,kernel="Laplace")
mu<-estimate$mu
lambda<-estimate$lambda
f<-dig(x,mu,lambda,kernel="Laplace")
l<-log(f)
Loglik<-sum(l)
}
if(kernel=="t"){
estimate<-mleIGt(x,nu.fixed)
mu<-estimate$mu
lambda<-estimate$lambda
nu<-estimate$nu
f<-dig(x,mu,lambda,kernel="t",nu)
l<-log(f)
Loglik<-sum(l)
}
return(Loglik)
}

